// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Db
{
    /// <summary> 玩家</summary>
    public partial class DBCharacter
    {
        public global::Server.Ygy.Game.Db.DBUserData UserData { get; set; }

        /// <summary> 账号数据</summary>
        public global::Server.Ygy.Game.Db.DBUserFriend UserFriend { get; set; }

        /// <summary> 好友</summary>
        public List<global::Server.Ygy.Game.Db.DBUserChatLog> UserChatLog { get; set; }

        /// <summary> 聊天记录</summary>
        public List<global::Server.Ygy.Game.Db.DBGameData> GameData { get; set; }

    }

    public partial class DBUserData
    {
        public global::Server.Ygy.Game.Db.DBUserCommonData CommonData { get; set; }

        /// <summary> 基本数据</summary>
        public global::Server.Ygy.Game.Db.DBUserFightData FightData { get; set; }

    }

    public partial class DBUserFightData
    {
        public int KillNum { get; set; }

        /// <summary> 杀敌数</summary>
        public int HeadShotNum { get; set; }

        /// <summary> 爆头数</summary>
        public int DeathNum { get; set; }

        /// <summary> 死亡数</summary>
        public long HarmNum { get; set; }

    }

    public partial class DBUserCommonData
    {
        public string Account { get; set; }

        /// <summary> 账号</summary>
        public string Password { get; set; }

        /// <summary> 密码</summary>
        public string PhoneNum { get; set; }

        /// <summary> 电话号</summary>
        public string Email { get; set; }

        /// <summary> 邮箱号</summary>
        public string Name { get; set; }

    }

    public partial class DBUserFriend
    {
        public List<string> Friends { get; set; }

    }

    public partial class DBUserChatLog
    {
        public string ReceiveAccount { get; set; }

        /// <summary> 接受者账号</summary>
        public string Msg { get; set; }

        /// <summary> 消息内容:文字或图片路径</summary>
        public string Date { get; set; }

    }

    public partial class DBGameData
    {
        public string StartDate { get; set; }

        /// <summary> 开始时间</summary>
        public string EndDate { get; set; }

        /// <summary> 结束时间</summary>
        public int KillNum { get; set; }

        /// <summary> 杀敌数</summary>
        public int HeadShotNum { get; set; }

        /// <summary> 爆头数</summary>
        public int DeathNum { get; set; }

        /// <summary> 死亡数</summary>
        public int HarmNum { get; set; }

    }

}
