// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Pb
{
    public partial class MSGIDCHAT
    {
        public int MSGIDCHATSENDREQUEST { get; set; }

        /// <summary> 发送消息请求</summary>
        public int MSGIDCHATSENDRESPONSE { get; set; }

        /// <summary> 发送消息回复</summary>
        public int MSGIDCHATSENDNOTIFY { get; set; }

        /// <summary> 发送消息通知</summary>
        public int MSGIDCHATSENDFRIENDREQUEST { get; set; }

        /// <summary> 发送好友添加请求</summary>
        public int MSGIDCHATSENDFRIENDRESPONSE { get; set; }

        /// <summary> 发送好友添加回复</summary>
        public int MSGIDCHATSENDFRIENDNOTIFY { get; set; }

        /// <summary> 好友添加通知</summary>
        public int MSGIDCHATFRIENDDATAREQUEST { get; set; }

        /// <summary> 好友列表请求</summary>
        public int MSGIDCHATFRIENDDATARESPONSE { get; set; }

    }

    /// <summary> 发送消息请求</summary>
    public partial class PBMsgChatSendRequest
    {
        public string ReceiveAccount { get; set; }

        /// <summary> 接受者账号</summary>
        public string Msg { get; set; }

        /// <summary> 消息</summary>
        public string Date { get; set; }

    }

    /// <summary> 发送消息回复</summary>
    public partial class PBMsgChatSendResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 发送消息通知</summary>
    public partial class PBMsgChatSendNotify
    {
        public string SendAccount { get; set; }

        /// <summary> 发送消息者</summary>
        public string Msg { get; set; }

        /// <summary> 消息内容</summary>
        public string Date { get; set; }

    }

    /// <summary> 发送好友请求</summary>
    public partial class PBMsgChatSendFriendRequest
    {
        public string DirAccount { get; set; }

    }

    /// <summary> 好友请求回复</summary>
    public partial class PBMsgChatSendFriendResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 添加好友通知</summary>
    public partial class PBMsgChatSendFriendNotify
    {
        public string RequestAccount { get; set; }

    }

    /// <summary> 好友列表请求</summary>
    public partial class PBMsgChatFriendDataRequest
    {
    }

    /// <summary> 好友列表回复</summary>
    public partial class PBMsgChatFriendDataResponse
    {
        public int ReturnCode { get; set; }

        public global::Server.Ygy.Game.Pb.PBMsgChatFriendDataList FriendList { get; set; }

    }

    /// <summary> 好友列表信息</summary>
    public partial class PBMsgChatFriendDataList
    {
        public List<string> Friends { get; set; }

    }

}
