// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Pb
{
    public partial class MSGIDCHAT
    {
        public int MSGIDCHATSENDREQUEST { get; set; }

        /// <summary> 发送消息请求</summary>
        public int MSGIDCHATSENDRESPONSE { get; set; }

        /// <summary> 发送消息回复</summary>
        public int MSGIDCHATSENDNOTIFY { get; set; }

        /// <summary> 发送消息通知</summary>
        public int MSGIDCHATSENDFRIENDREQUEST { get; set; }

        /// <summary> 发送好友添加请求</summary>
        public int MSGIDCHATSENDFRIENDRESPONSE { get; set; }

        /// <summary> 发送好友添加回复</summary>
        public int MSGIDCHATSENDFRIENDNOTIFY { get; set; }

        /// <summary> 好友添加通知</summary>
        public int MSGIDCHATFRIENDDATAREQUEST { get; set; }

        /// <summary> 好友列表请求</summary>
        public int MSGIDCHATFRIENDDATARESPONSE { get; set; }

        /// <summary> 好友列表回复</summary>
        public int MSGIDCHATFRIENDMSGLOGREQUEST { get; set; }

        /// <summary> 好友消息记录列表请求.</summary>
        public int MSGIDCHATFRIENDMSGLOGRESPONSE { get; set; }

        /// <summary> 好友消息记录列表回复</summary>
        public int MSGIDCHATSELFMSGLOGREQUEST { get; set; }

        /// <summary> 玩家发送给好友的聊天记录请求</summary>
        public int MSGIDCHATSELFMSGLOGRESPONSE { get; set; }

        /// <summary> 玩家发送给好友的聊天记录回复</summary>
        public int MSGIDCHATUSERDATAREQUEST { get; set; }

        /// <summary> 用户数据查询请求</summary>
        public int MSGIDCHATUSERDATARESPONSE { get; set; }

        /// <summary> 用户数据查询回复</summary>
        public int MSGIDCHATANSWERADDFRIENDREQUEST { get; set; }

        /// <summary> 回应他人的添加好友请求</summary>
        public int MSGIDCHATANSWERADDFRIENDRESPONSE { get; set; }

        /// <summary> 回应他人的添加好友回复</summary>
        public int MSGIDCHATANSWERADDFRIENDNOTIFY { get; set; }

    }

    /// <summary> 发送消息请求</summary>
    public partial class PBMsgChatSendRequest
    {
        public string ReceiveAccount { get; set; }

        /// <summary> 接受者账号</summary>
        public string Msg { get; set; }

        /// <summary> 消息</summary>
        public long Date { get; set; }

    }

    /// <summary> 发送消息回复</summary>
    public partial class PBMsgChatSendResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 发送消息通知</summary>
    public partial class PBMsgChatSendNotify
    {
        public string SendAccount { get; set; }

        /// <summary> 发送消息者</summary>
        public string Msg { get; set; }

        /// <summary> 消息内容</summary>
        public long Date { get; set; }

        /// <summary> 发送时间</summary>
        public string ReceiveAccount { get; set; }

    }

    /// <summary> 发送添加好友请求</summary>
    public partial class PBMsgChatSendFriendRequest
    {
        public string DirAccount { get; set; }

    }

    /// <summary> 添加好友请求回复</summary>
    public partial class PBMsgChatSendFriendResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 添加好友通知</summary>
    public partial class PBMsgChatSendFriendNotify
    {
        public string RequestAccount { get; set; }

        /// <summary> 发送者账号</summary>
        public string RequestName { get; set; }

    }

    /// <summary> 好友列表请求</summary>
    public partial class PBMsgUserFriendListRequest
    {
    }

    /// <summary> 好友列表回复</summary>
    public partial class PBMsgUserFriendListResponse
    {
        public int ReturnCode { get; set; }

        public List<global::Server.Ygy.Game.Pb.PBMsgFriendInfo> Friends { get; set; }

    }

    public partial class PBMsgFriendInfo
    {
        public string Account { get; set; }

        public string Name { get; set; }

        public string UserImg { get; set; }

    }

    /// <summary> 好友聊天记录请求</summary>
    public partial class PBMsgFriendChatMsgLogRequest
    {
    }

    /// <summary> 好友聊天记录回复</summary>
    public partial class PBMsgFriendChatMsgLogResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgFriendChatMsg> Msgs { get; set; }

    }

    public partial class PBMsgFriendChatMsg
    {
        public string Account { get; set; }

        public List<global::Server.Ygy.Game.Pb.PBMsgChatMsg> ChatMsgs { get; set; }

    }

    /// <summary> 聊天记录</summary>
    public partial class PBMsgChatMsg
    {
        public string Msg { get; set; }

        /// <summary> 消息内容</summary>
        public long Date { get; set; }

    }

    /// <summary> 玩家自身发送的聊天记录请求</summary>
    public partial class PBMsgSelfSendChatMsgLogRequest
    {
    }

    /// <summary> 玩家自身发送的聊天记录回复</summary>
    public partial class PBMsgSelfSendChatMsgLogResponse
    {
        public int ReturnCode { get; set; }

        /// <summary>返回码</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgFriendChatMsg> Msgs { get; set; }

    }

    /// <summary> 查询用户数据请求</summary>
    public partial class PBMsgSelectUserDataRequest
    {
        public string Account { get; set; }

        /// <summary> 关键词，账号，或者用户名</summary>
        public string Name { get; set; }

    }

    /// <summary> 查询用户数据回复</summary>
    public partial class PBMsgSelectUserDataResponse
    {
        public int ReturnCode { get; set; }

        public List<global::Server.Ygy.Game.Pb.PBMsgFriendInfo> Users { get; set; }

    }

    /// <summary> 回复他人的添加好友请求</summary>
    public partial class PBMsgAnswerAddFriendRequest
    {
        public string AnswerAccount { get; set; }

        /// <summary> 好友请求者账号</summary>
        public bool Result { get; set; }

    }

    /// <summary> 回应他人的添加好友回复</summary>
    public partial class PBMsgAnswerAddFriendResponse
    {
        public int ReturnCode { get; set; }

        public global::Server.Ygy.Game.Pb.PBMsgFriendInfo FriendInfo { get; set; }

    }

    /// <summary> 回应他人的添加好友回复 , 服务器发送给 发起好友请求的用户</summary>
    public partial class PBMsgAnswerAddFriendNotify
    {
        public global::Server.Ygy.Game.Pb.PBMsgFriendInfo AddFriendInfo { get; set; }

    }

}
