// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Pb
{
    /// <summary>
    /// <para> 定义在那个包</para>
    /// <para> 解释字段定义</para>
    /// </summary>
    public partial class Descript
    {
        public string Desc { get; set; }

    }

    /// <summary> 在这个文件中定义所有的枚举</summary>
    public enum EWeaponType
    {
        EWeaponType_NONE = 0,
        EWeaponType_MAIN = 1,
        /// <summary> 主武器</summary>
        EWeaponType_SUB = 2,
        /// <summary> 副武器</summary>
        EWeaponType_KNIFE = 3,
        /// <summary> 近战武器</summary>
        EWeaponType_GRENADE = 4,
    }


    public enum MSGID
    {
        /// <summary>login</summary>
        MSGID_LOGIN_REQUEST = 65553,
        /// <summary> 登陆请求</summary>
        MSGID_LOGIN_RESPONSE = 65554,
        /// <summary> 登陆回复</summary>
        MSGID_REGISTER_REQUEST = 65569,
        /// <summary> 注册请求</summary>
        MSGID_REGISTER_RESPONSE = 65570,
        /// <summary> 注册回复</summary>
        MSGID_AFFIRM_LOGIN_REQUEST = 65585,
        /// <summary> 確認登陸請求</summary>
        MSGID_AFFIRM_LOGIN_RESPONSE = 65586,
        /// <summary>
        /// <para> 確認登陸回復</para>
        /// <para> chat</para>
        /// </summary>
        MSGID_CHAT_SEND_REQUEST = 131089,
        /// <summary> 发送消息请求</summary>
        MSGID_CHAT_SEND_RESPONSE = 131090,
        /// <summary> 发送消息回复</summary>
        MSGID_CHAT_SEND_NOTIFY = 131088,
        /// <summary> 发送消息通知</summary>
        MSGID_CHAT_SEND_FRIEND_REQUEST = 131105,
        /// <summary> 发送好友添加请求</summary>
        MSGID_CHAT_SEND_FRIEND_RESPONSE = 131106,
        /// <summary> 发送好友添加回复</summary>
        MSGID_CHAT_SEND_FRIEND_NOTIFY = 131104,
        /// <summary> 好友添加通知</summary>
        MSGID_CHAT_FRIEND_DATA_REQUEST = 131121,
        /// <summary> 好友列表请求</summary>
        MSGID_CHAT_FRIEND_DATA_RESPONSE = 131122,
        /// <summary> 好友列表回复</summary>
        MSGID_CHAT_FRIEND_MSG_LOG_REQUEST = 131137,
        /// <summary> 好友消息记录列表请求.</summary>
        MSGID_CHAT_FRIEND_MSG_LOG_RESPONSE = 131138,
        /// <summary> 好友消息记录列表回复</summary>
        MSGID_CHAT_SELF_MSG_LOG_REQUEST = 131153,
        /// <summary> 玩家发送给好友的聊天记录请求</summary>
        MSGID_CHAT_SELF_MSG_LOG_RESPONSE = 131154,
        /// <summary> 玩家发送给好友的聊天记录回复</summary>
        MSGID_CHAT_USER_DATA_REQUEST = 131169,
        /// <summary> 用户数据查询请求</summary>
        MSGID_CHAT_USER_DATA_RESPONSE = 131170,
        /// <summary> 用户数据查询回复</summary>
        MSGID_CHAT_ANSWER_ADD_FRIEND_REQUEST = 131185,
        /// <summary> 回应他人的添加好友请求</summary>
        MSGID_CHAT_ANSWER_ADD_FRIEND_RESPONSE = 131186,
        /// <summary> 回应他人的添加好友回复</summary>
        MSGID_CHAT_ANSWER_ADD_FRIEND_NOTIFY = 131184,
        /// <summary>
        /// <para> 回应他人的添加好友通知</para>
        /// <para> hall</para>
        /// </summary>
        MSGID_HALL_CHANGE_USER_IMG_REQUEST = 196625,
        /// <summary> 请求更换头像</summary>
        MSGID_HALL_CHANGE_USER_IMG_RESPONSE = 196626,
        /// <summary> 更换头像回复</summary>
        MSGID_HALL_USER_DATA_REQUEST = 196641,
        /// <summary> 用户数据请求</summary>
        MSGID_HALL_USER_DATA_RESPONSE = 196642,
        /// <summary> 用户数据回复</summary>
        MSGID_HALL_USER_GAME_RECORD_REQUEST = 196657,
        /// <summary> 用户对局数据请求</summary>
        MSGID_HALL_USER_GAME_RECORD_RESPONSE = 196658,
        /// <summary> 用户对局数据回复</summary>
        MSGID_HALL_GET_ALL_RANK_LIST_REQUEST = 196673,
        /// <summary> 请求获得全网排位排名</summary>
        MSGID_HALL_GET_ALL_RANK_LIST_RESPONSE = 196674,
        /// <summary> 回复获得全网排位排名</summary>
        MSGID_HALL_GET_ALL_RANK_LIST_NOTIFY = 196672,
        /// <summary> 通知获得全网排位排名</summary>
        MSGID_HALL_START_MATCHING_REQUEST = 196689,
        /// <summary> 开始匹配请求</summary>
        MSGID_HALL_START_MATCHING_RESPONSE = 196690,
        /// <summary> 开始匹配回复</summary>
        MSGID_HALL_START_MATCHING_NOTIFY = 196688,
        /// <summary> 开始匹配通知</summary>
        MSGID_HALL_CANCEL_MATCHING_REQUEST = 196705,
        /// <summary> 取消匹配请求</summary>
        MSGID_HALL_CANCEL_MATCHING_RESPONSE = 196706,
        /// <summary> 取消匹配回复</summary>
        MSGID_HALL_CHANGE_USER_NAME_REQUEST = 196721,
        /// <summary> 请求修改用户名称</summary>
        MSGID_HALL_CHANGE_USER_NAME_RESPONSE = 196722,
        /// <summary> 修改用户名称回复</summary>
        MSGID_HALL_GAME_START_REQUEST = 196737,
        /// <summary> 开始游戏请求</summary>
        MSGID_HALL_GAME_START_RESPONSE = 196738,
        /// <summary> 开始游戏回复</summary>
        MSGID_HALL_GAME_START_NOTIFY = 196736,
        /// <summary> 开始游戏通知</summary>
        MSGID_HALL_GAME_RUNNING_NOTIFY = 196752,
        /// <summary> 对局运行中通知</summary>
        MSGID_HALL_GAME_RUNNING_REQUEST = 196753,
        /// <summary> 请求转发对局操作</summary>
        MSGID_HALL_GAME_RUNNING_RESPONSE = 196754,
        /// <summary> 转发对局操作回复</summary>
        MSGID_HALL_EXIT_GAME_REQUEST = 196769,
        /// <summary> 退出游戏请求</summary>
        MSGID_HALL_EXIT_GAME_RESPONSE = 196770,
        /// <summary> 退出游戏回复</summary>
        MSGID_HALL_CHOSE_PACKAGE_REQUEST = 196785,
        /// <summary> 选择背包请求</summary>
        MSGID_HALL_CHOSE_PACKAGE_RESPONSE = 196786,
        /// <summary> 选择背包回复</summary>
        MSGID_HALL_CHOSE_SKILL_REQUEST = 196801,
        /// <summary> 选择技能请求</summary>
        MSGID_HALL_CHOSE_SKILL_RESPONSE = 196802,
        /// <summary> 选择技能回复</summary>
        MSGID_HALL_ROOM_HOST_IP_NOTIFY = 196816,
        /// <summary> 房主地址通知</summary>
        MSGID_HALL_HOST_CONNECTED_REPORT = 196819,
    }


}
