// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Pb
{
    public partial class MSGIDHALL
    {
        public int MSGIDHALLCHANGEUSERIMGREQUEST { get; set; }

        /// <summary> 请求更换头像</summary>
        public int MSGIDHALLCHANGEUSERIMGRESPONSE { get; set; }

        /// <summary> 更换头像回复</summary>
        public int MSGIDHALLUSERDATAREQUEST { get; set; }

        /// <summary> 用户数据请求</summary>
        public int MSGIDHALLUSERDATARESPONSE { get; set; }

        /// <summary> 用户数据回复</summary>
        public int MSGIDHALLUSERGAMERECORDREQUEST { get; set; }

        /// <summary> 用户对局数据请求</summary>
        public int MSGIDHALLUSERGAMERECORDRESPONSE { get; set; }

        /// <summary> 用户对局数据回复</summary>
        public int MSGIDHALLGETALLRANKLISTREQUEST { get; set; }

        /// <summary> 请求获得全网排位排名</summary>
        public int MSGIDHALLGETALLRANKLISTRESPONSE { get; set; }

        /// <summary> 回复获得全网排位排名</summary>
        public int MSGIDHALLGETALLRANKLISTNOTIFY { get; set; }

        /// <summary> 通知获得全网排位排名</summary>
        public int MSGIDHALLSTARTMATCHINGREQUEST { get; set; }

        /// <summary> 开始匹配请求</summary>
        public int MSGIDHALLSTARTMATCHINGRESPONSE { get; set; }

        /// <summary> 开始匹配回复</summary>
        public int MSGIDHALLSTARTMATCHINGNOTIFY { get; set; }

        /// <summary> 开始匹配通知</summary>
        public int MSGIDHALLCANCELMATCHINGREQUEST { get; set; }

        /// <summary> 取消匹配请求</summary>
        public int MSGIDHALLCANCELMATCHINGRESPONSE { get; set; }

        /// <summary> 取消匹配回复</summary>
        public int MSGIDHALLCHANGEUSERNAMEREQUEST { get; set; }

        /// <summary> 请求修改用户名称</summary>
        public int MSGIDHALLCHANGEUSERNAMERESPONSE { get; set; }

        /// <summary> 修改用户名称回复</summary>
        public int MSGIDHALLGAMESTARTREQUEST { get; set; }

        /// <summary> 开始游戏请求</summary>
        public int MSGIDHALLGAMESTARTRESPONSE { get; set; }

        /// <summary> 开始游戏回复</summary>
        public int MSGIDHALLGAMESTARTNOTIFY { get; set; }

        /// <summary> 开始游戏通知</summary>
        public int MSGIDHALLGAMERUNNINGNOTIFY { get; set; }

        /// <summary> 对局运行中通知</summary>
        public int MSGIDHALLGAMERUNNINGREQUEST { get; set; }

        /// <summary> 请求转发对局操作</summary>
        public int MSGIDHALLGAMERUNNINGRESPONSE { get; set; }

        /// <summary> 转发对局操作回复</summary>
        public int MSGIDHALLEXITGAMEREQUEST { get; set; }

        /// <summary> 退出游戏请求</summary>
        public int MSGIDHALLEXITGAMERESPONSE { get; set; }

        /// <summary> 退出游戏回复</summary>
        public int MSGIDHALLCHOSEPACKAGEREQUEST { get; set; }

        /// <summary> 选择背包请求</summary>
        public int MSGIDHALLCHOSEPACKAGERESPONSE { get; set; }

        /// <summary> 选择背包回复</summary>
        public int MSGIDHALLCHOSESKILLREQUEST { get; set; }

        /// <summary> 选择技能请求</summary>
        public int MSGIDHALLCHOSESKILLRESPONSE { get; set; }

        /// <summary> 选择技能回复</summary>
        public int MSGIDHALLROOMHOSTIPNOTIFY { get; set; }

        /// <summary> 房主地址通知</summary>
        public int MSGIDHALLHOSTCONNECTEDREPORT { get; set; }

    }

    public partial class PBMsgChangeUserImgRequest
    {
        public string NewUserImg { get; set; }

    }

    public partial class PBMsgChangeUserImgResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public string NewUserImg { get; set; }

    }

    /// <summary> 用户数据请求</summary>
    public partial class PBMsgUserDataRequest
    {
    }

    /// <summary> 用户数据回复</summary>
    public partial class PBMsgUserDataResponse
    {
        public int ReturnCode { get; set; }

        public global::Server.Ygy.Game.Pb.PBMsgUserData UserData { get; set; }

    }

    /// <summary> 用户数据</summary>
    public partial class PBMsgUserData
    {
        public string Account { get; set; }

        /// <summary> 账号</summary>
        public string PhoneNum { get; set; }

        /// <summary> 电话号</summary>
        public string Email { get; set; }

        /// <summary> 邮箱号</summary>
        public string Name { get; set; }

        /// <summary> 姓名</summary>
        public string UserImg { get; set; }

        /// <summary> 用户头像</summary>
        public int KillNum { get; set; }

        /// <summary> 杀敌数</summary>
        public int HeadShotNum { get; set; }

        /// <summary> 爆头数</summary>
        public int DeathNum { get; set; }

        /// <summary> 死亡数</summary>
        public long HarmNum { get; set; }

    }

    /// <summary> 用户对局数据请求</summary>
    public partial class PBMsgUserGameRecordRequest
    {
    }

    /// <summary> 用户对局数据回复</summary>
    public partial class PBMsgUserGameRecordResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgGameRecordInfo> Info { get; set; }

    }

    public partial class PBMsgGameRecordInfo
    {
        public long Id { get; set; }

        /// <summary> 对局id</summary>
        public long StartDate { get; set; }

        /// <summary> 开始时间</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgGameData> Info { get; set; }

    }

    public partial class PBMsgGameData
    {
        public long EndDate { get; set; }

        /// <summary> 死亡时间</summary>
        public int KillNum { get; set; }

        /// <summary> 杀敌数</summary>
        public int HeadShotNum { get; set; }

        /// <summary> 爆头数</summary>
        public int DeathNum { get; set; }

        /// <summary> 死亡数</summary>
        public int HarmNum { get; set; }

        /// <summary> 伤害数值</summary>
        public int Rank { get; set; }

        /// <summary> 排名</summary>
        public string Name { get; set; }

        /// <summary> 名称</summary>
        public string Account { get; set; }

    }

    /// <summary> 请求获得全网排名前十列表</summary>
    public partial class PBMsgGetAllRankRequest
    {
    }

    /// <summary> 回复获得全网排名前十列表</summary>
    public partial class PBMsgGetAllRankResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgGameData> Info { get; set; }

    }

    /// <summary> 通知全网排名前十列表</summary>
    public partial class PBMsgGetAllRankNotify
    {
        public List<global::Server.Ygy.Game.Pb.PBMsgGameData> Info { get; set; }

    }

    /// <summary> 开始匹配请求</summary>
    public partial class PBMsgStartMatchingRequest
    {
        public string Account { get; set; }

    }

    /// <summary> 开始匹配回复</summary>
    public partial class PBMsgStartMatchingResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public int RoomPlayerCount { get; set; }

        /// <summary> 当前加入房间人数</summary>
        public long RoomId { get; set; }

    }

    /// <summary> 开始匹配通知</summary>
    public partial class PBMsgStartMatchingNotify
    {
        public bool IsOpen { get; set; }

        /// <summary> 是否开始游戏</summary>
        public int LeaveTime { get; set; }

        /// <summary> 倒计时</summary>
        public int RoomPlayerCount { get; set; }

    }

    /// <summary> 取消匹配请求</summary>
    public partial class PBMsgCancelMatchingRequest
    {
        public string Account { get; set; }

        /// <summary> 取消匹配的用户账号</summary>
        public long RoomId { get; set; }

    }

    /// <summary> 取消匹配回复</summary>
    public partial class PBMsgCancelMatchingResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 修改用户名称请求</summary>
    public partial class PBMsgChangeUserNameRequest
    {
        public string Account { get; set; }

        /// <summary> 账号</summary>
        public string Name { get; set; }

    }

    /// <summary> 修改用户名称回复</summary>
    public partial class PBMsgChangeUserNameResponse
    {
        public int ReturnCode { get; set; }

        public string Name { get; set; }

    }

    /// <summary> 开始游戏请求</summary>
    public partial class PBMsgStartGameRequest
    {
        public string Account { get; set; }

        /// <summary> 客户端账号</summary>
        public long RoomId { get; set; }

    }

    /// <summary> 开始游戏回复</summary>
    public partial class PBMsgStartGameResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 玩家基本信息</summary>
    public partial class PBMsgPlayerInfo
    {
        public string Account { get; set; }

        public int PackageId { get; set; }

        public int SkillId { get; set; }

        public string Name { get; set; }

    }

    /// <summary> 开始游戏通知</summary>
    public partial class PBMsgStartGameNotify
    {
        public long InitFrameCount { get; set; }

        /// <summary> 初始帧数</summary>
        public int FlushTime { get; set; }

        /// <summary> 服务端刷新频率</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgPlayerInfo> Players { get; set; }

    }

    /// <summary> 对局运行中通知</summary>
    public partial class PBMsgGameRunningNotify
    {
        public long CurrentFrameCount { get; set; }

        /// <summary> 当前服务端帧数</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgPlayerOption> Options { get; set; }

        /// <summary> 操作列表</summary>
        public int FlushTime { get; set; }

    }

    /// <summary> 对局运行中请求(客户端向服务器请求转发操作)</summary>
    public partial class PBMsgGameRunningRequest
    {
        public long RoomId { get; set; }

        public global::Server.Ygy.Game.Pb.PBMsgPlayerOption Option { get; set; }

    }

    /// <summary> 玩家操作</summary>
    public partial class PBMsgPlayerOption
    {
        public string Account { get; set; }

        /// <summary> 玩家账号</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgOption> PlayerOption { get; set; }

        /// <summary> 玩家操作</summary>
        public long FrameCount { get; set; }

    }

    /// <summary> 操作</summary>
    public partial class PBMsgOption
    {
        public global::Server.Ygy.Game.Pb.EOptionType OptionType { get; set; }

        /// <summary> 操作类型</summary>
        public global::Server.Ygy.Game.Pb.EOptionTypeReal InputType { get; set; }

        /// <summary> 操作具体字符</summary>
        public bool ValueBool { get; set; }

        /// <summary> 按键值</summary>
        public float ValueFloat { get; set; }

        /// <summary> 操作值</summary>
        public long ClientFrameCount { get; set; }

    }

    /// <summary> 对局运行中回复</summary>
    public partial class PBMsgGameRunningResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 退出游戏请求</summary>
    public partial class PBMsgExitGameRequest
    {
        public long RoomId { get; set; }

        /// <summary> 房间id</summary>
        public global::Server.Ygy.Game.Pb.PBMsgGameData GameData { get; set; }

    }

    /// <summary> 退出游戏回复</summary>
    public partial class PBMsgExitGameResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 选择背包请求</summary>
    public partial class PBMsgChosePackageRequest
    {
        public long RoomId { get; set; }

        /// <summary> 房间id</summary>
        public string Account { get; set; }

        /// <summary> 账号</summary>
        public int PackageId { get; set; }

    }

    /// <summary> 选择背包回复</summary>
    public partial class PBMsgChosePackageResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public string Account { get; set; }

        public int PackageId { get; set; }

    }

    /// <summary> 选择技能请求   TODO 待完成</summary>
    public partial class PBMsgChoseSkillRequest
    {
        public long RoomId { get; set; }

        /// <summary> 房间id</summary>
        public string Account { get; set; }

        /// <summary> 账号</summary>
        public int SkillId { get; set; }

    }

    /// <summary> 选择技能回复</summary>
    public partial class PBMsgChoseSkillResponse
    {
        public int ReturnCode { get; set; }

        /// <summary> 返回码</summary>
        public string Account { get; set; }

        public int SkillId { get; set; }

    }

    /// <summary>
    /// <para> 采用Mirror进行游戏状态同步</para>
    /// <para> 房主ip地址通知</para>
    /// </summary>
    public partial class PBMsgRoomHostIPAddressNotify
    {
        public string IpAddress { get; set; }

        /// <summary> 房主地址</summary>
        public string HostAccount { get; set; }

        /// <summary> 房主账号</summary>
        public List<global::Server.Ygy.Game.Pb.PBMsgPlayerInfo> Players { get; set; }

    }

    /// <summary> 连接房主结果上报</summary>
    public partial class PBMsgHostConnectedReport
    {
        public bool IsConnected { get; set; }

        /// <summary> 是否连接成功</summary>
        public string Account { get; set; }

        public long RoomId { get; set; }

    }

    /// <summary> 操作类型</summary>
    public enum EOptionType
    {
        EOptionType_NONE = 0,
        EOptionType_Axis = 1,
        EOptionType_ButtonDown = 2,
        EOptionType_KeyDown = 3,
    }


    /// <summary> 操作具体类型</summary>
    public enum EOptionTypeReal
    {
        EOptionTypeReal_None = 0,
        EOptionTypeReal_Shoot = 1,
        /// <summary> 射击</summary>
        EOptionTypeReal_ForwardOrBack = 2,
        /// <summary> 前进后退</summary>
        EOptionTypeReal_RightOrLeft = 3,
        /// <summary> 向左向右</summary>
        EOptionTypeReal_Jump = 4,
        /// <summary> 跳跃</summary>
        EOptionTypeReal_Reload = 5,
        /// <summary> 换弹</summary>
        EOptionTypeReal_OpenMirror = 6,
        /// <summary> 开镜</summary>
        EOptionTypeReal_ChangeMainWeapon = 7,
        /// <summary> 切换主武器</summary>
        EOptionTypeReal_ChangeSubWeapon = 8,
        /// <summary> 切换副武器</summary>
        EOptionTypeReal_ChangeLastWeapon = 9,
        /// <summary> 切换上一个武器</summary>
        EOptionTypeReal_MouseX = 10,
        /// <summary> 横向移动鼠标</summary>
        EOptionTypeReal_MouseY = 11,
    }


}
