// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Server.Ygy.Game.Pb
{
    public partial class MSGIDLOGIN
    {
        public int MSGIDLOGINREQUEST { get; set; }

        /// <summary> 登陆请求</summary>
        public int MSGIDLOGINRESPONSE { get; set; }

        /// <summary> 登陆回复</summary>
        public int MSGIDREGISTERREQUEST { get; set; }

        /// <summary> 注册请求</summary>
        public int MSGIDREGISTERRESPONSE { get; set; }

        /// <summary> 注册回复</summary>
        public int MSGIDAFFIRMLOGINREQUEST { get; set; }

        /// <summary> 確認登陸請求</summary>
        public int MSGIDAFFIRMLOGINRESPONSE { get; set; }

    }

    /// <summary> 登陆请求</summary>
    public partial class PBMsgLoginRequest
    {
        public string Account { get; set; }

        public string UserPassword { get; set; }

    }

    /// <summary> 登陆回复</summary>
    public partial class PBMsgLoginResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 注册请求</summary>
    public partial class PBMsgRegisterRequest
    {
        public string Account { get; set; }

        public string UserPassword { get; set; }

    }

    /// <summary> 注册回复</summary>
    public partial class PBMsgRegisterResponse
    {
        public int ReturnCode { get; set; }

    }

    /// <summary> 確認登陸請求</summary>
    public partial class PBMsgAffirmLoginRequest
    {
        public string Account { get; set; }

    }

    /// <summary> 確認登陸回復</summary>
    public partial class PBMsgAffirmLoginResponse
    {
        public int ReturnCode { get; set; }

    }

}
